- name: Copy IEC 61850 Files to all clients
  hosts: sensors
  strategy: linear
  #default, wait for Task to finish on all hosts
  gather_facts: yes
  tasks:
    - name: Delete old folder
      file:
        state: absent
        path: /home/rock/IEC 61850

    - name: Copy IEC 61850 folder
      # synchronize (rsync) is way quicker than copy https://stackoverflow.com/questions/27985334/why-is-copying-a-directory-with-ansible-so-slow
      synchronize:
        src: /home/lucas/masterarbeit/IEC 61850
        dest: /home/rock

    - name: ls on folder
      shell: ls /home/rock/IEC\ 61850
      register: output_iec61850
    - debug:
        msg: "{{ output_iec61850.stdout_lines }}"

    - name: Delete old sample data file
      file:
        state: absent
        path: /home/rock/sample_data.csv

    - name: Copy sample data file
      synchronize:
        src: /home/lucas/masterarbeit/sample_data.csv
        dest: /home/rock/sample_data.csv
    
    - name: ls on sample_data location
      shell: ls /home/rock
      register: output_data
    - debug:
        msg: "{{ output_data.stdout_lines }}"
