version: "3.0"

services:
  iec104_trafostation:
    build: .
    hostname: iec104_trafostation
    volumes:
      - ./Trafostation.py:/work/Trafostation.py
      - ../sample_data.csv:/work/sample_data.csv
    ports:
    - "2404:2404"
    working_dir: /work
    command: /bin/sh -c "python3 /work/Trafostation.py"
    # For Output
    stdin_open: true
    tty: true
    
  iec104_scada:
    build: .
    hostname: iec104_scada
    volumes:
      - ./SCADA_balanced.py:/work/SCADA.py
      - ./templates/index.html:/work/templates/index.html
    #depends_on:
    #  - iec104_trafostation
    ports:
      - "5000:5000"
    working_dir: /work
    command: /bin/sh -c "python3 /work/SCADA.py" # flask --app --debugger /work/Client.py run"
    environment:
      - SERVERIP=10.20.111.237,10.20.111.234,10.20.111.235,10.20.111.238,10.20.111.236 #iec104_trafostation
      - TCPPORT=2404
    # For Output
    stdin_open: true
    tty: true