- name: Copy all files to the server
  hosts: server
  gather_facts: yes
  tasks:
    - name: Copy all experiment files
      # synchronize (rsync) is way quicker than copy https://stackoverflow.com/questions/27985334/why-is-copying-a-directory-with-ansible-so-slow
      synchronize:
        src: /home/lucas/masterarbeit/
        dest: /root/master/

    - name: ls on folder
      shell: ls /root/master/
      register: output
    - debug:
        msg: "{{ output.stdout_lines }}"