- name: Reboot all Sensors
  hosts: sensors
  strategy: linear
  #default, wait for Task to finish on all hosts
  gather_facts: yes
  tasks:
   - name: Reboot Sensors and wait for 30s for them to come back online
     reboot:
       msg: "Reboot all Sensors"
       connect_timeout: 5
       reboot_timeout: 600
       pre_reboot_delay: 0
       post_reboot_delay: 30
       test_command: whoami

