- name: Stress the ppp0 interface with 100MB of testdata
  hosts: sensors
  strategy: linear 
  #default, wait for Task to finish on all hosts
  gather_facts: yes
  tasks:
   - name: Is PPP Interface up?
     set_fact: 
       lte_adapter: '{{ item }}'
     loop: '{{ ansible_facts.interfaces }}'
     when: 'item.startswith("ppp")'

   - name: Start PPP Script
     shell: pppd call quectel-ppp &
     async: 10
     when: lte_adapter is not defined

   - name: PPP details
     shell: ip a | grep ppp0
     register: ppp_output
     ignore_errors: yes

   - name: Output from task
     debug:
       msg: "{{ ppp_output.stdout_lines }}"

   - name: Set Route for Speedtest
     shell: route add -host 88.198.248.254 dev ppp0
     ignore_errors: yes

   - name: Remove old File
     shell: rm 100MB.bin
     ignore_errors: yes

   - name: Download 100MB Testfile from Hetzner
     shell: wget --inet4-only https://speed.hetzner.de/100MB.bin

   - name: Remove File
     shell: rm 100MB.bin

   - name: Stop PPP Script
     shell: killall -9 pppd wget
     become: yes
     when: lte_adapter is defined and lte_adapter == "ppp0"
     ignore_errors: yes

   - name: PPP details
     shell: ip a | grep ppp0
     register: ppp_output
     # grep return error when empty
     failed_when: "ppp_output.rc == 2"
     ignore_errors: yes
   - debug:
       msg: "Success"
     when: ppp_output.stdout == ""
   - debug:
       msg: "{{ ppp_output.stdout }}"
     when: ppp_output.stdout != ""